import { asset } from './assets';
import {NeuralBackground, NeuralCore, Education, ExperienceCards, ResearchMetrics} from './Enhancements';
import {useState} from 'react';import {Github,Linkedin,Mail,ExternalLink,CalendarDays,Trophy,MapPin} from 'lucide-react';import {motion,MotionConfig} from 'framer-motion';import {projects,certificates} from './data/content';
const fade={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.55}};
const Title=({n,k,t,d})=><div className="section-head"><div><div className="kicker">{n} — {k}</div><h2>{t}</h2></div>{d&&<p>{d}</p>}</div>;
export default function App(){const[p,setP]=useState(null),[c,setC]=useState(null);return <MotionConfig reducedMotion="user"><NeuralBackground/><nav><a className="brand" href="#home">SB<span>.</span></a><div className="links">{['about','experience','projects','research','achievements','skills','contact'].map(x=><a key={x} href={'#'+x}>{x}</a>)}</div><div className="social"><a href="https://github.com/shurooqbawazir4" target="_blank" rel="noopener noreferrer"><Github/></a><a href="https://www.linkedin.com/in/shurooq-bawazir/" target="_blank" rel="noopener noreferrer"><Linkedin/></a></div></nav><main>
<section id="home" className="hero section"><motion.div {...fade}><div className="eyebrow">AI ENGINEER · MACHINE LEARNING · DATA SCIENCE</div><h1>Shurooq<br/><em>Bawazir</em></h1><p>I build intelligent systems that turn research, data and AI models into practical products with measurable real-world impact.</p><div className="actions"><a className="btn primary" href="#projects">Explore my work</a><a className="btn" href="mailto:shurooqbawazir@gmail.com"><Mail/>Contact me</a></div></motion.div><NeuralCore/></section>
<section className="stats"><div><b>1st</b><span>Creative Sparks 2026</span></div><div><b>2nd</b><span>ACM AI Hackathon 2025</span></div><div><b>Top 50</b><span>AI League by SCAI</span></div><div><b>Published</b><span>Peer-reviewed AI research</span></div></section>
<section id="about" className="section about-section">
  <div className="kicker">01 — ABOUT</div>
  <div className="about-layout">
    <motion.figure className="about-photo" {...fade}>
      <img src={asset('hydromap_presentation.jpeg')} alt="Shurooq Bawazir presenting HydroMap on stage at the Creative Sparks Challenge" loading="lazy" width="1170" height="1538"/>
      <figcaption><span>RESEARCH INTO REAL-WORLD IMPACT</span>Presenting HydroMap · Creative Sparks Challenge</figcaption>
    </motion.figure>
    <motion.div className="about-copy" {...fade}>
      <h2>Applied AI with a product mindset.</h2>
      <p className="lead">Computer Science graduate from Prince Sultan University, specializing in Artificial Intelligence and Data Science. Graduated with First-Class Honors and a GPA of 3.83/4.00, with a strong analytical foundation demonstrated by achieving 98% on the General Aptitude Test. Experienced in developing practical AI solutions across machine learning, computer vision, large language models, intelligent agents, and data analytics, with a focus on transforming complex ideas into reliable, user-centered applications.</p>
      <Education/>
      <div className="pills">{['Artificial Intelligence','Machine Learning','Computer Vision','LLMs & Agents','Data Science','AI Product Development'].map(x=><span key={x}>{x}</span>)}</div>
    </motion.div>
  </div>
</section>
<section id="experience" className="section"><Title n="02" k="EXPERIENCE" t="From models to real systems." d="Technical depth, practical implementation and clear communication."/><ExperienceCards/></section>
<section id="projects" className="section"><Title n="03" k="FEATURED PROJECTS" t="AI systems built for real-world impact." d="Click any project to explore the case study."/><div className="projects">{projects.map((x,i)=><motion.article key={x.id} {...fade} className="project" role="button" tabIndex={0} aria-label={"Explore "+x.title} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setP(x)}}} onClick={()=>setP(x)}>{x.cover&&<img src={x.cover} alt={x.title+" project preview"} loading="lazy"/>}<div className="shade"/><div className="project-text"><small>{x.category} · 0{i+1}</small><h3>{x.title}</h3><p>{x.tagline}</p><b>{x.award}</b></div></motion.article>)}</div></section>
<section id="research" className="section"><Title n="04" k="RESEARCH" t="Published research, evaluated with real metrics."/><motion.article className="research" {...fade}><ResearchMetrics/><div><small>EUROPEAN SCIENTIFIC JOURNAL · 2024</small><h2>DeepLeaf</h2><h3>Automated Leaf Classification Using Neural Networks</h3><p>Peer-reviewed research on automated leaf classification using neural-network-based image processing. The study used 600 images across 20 leaf classes with preprocessing, noise augmentation, binarization and model evaluation.</p><a className="btn" href={asset('DeepLeaf_paper.pdf')} target="_blank" rel="noopener noreferrer">Read publication <ExternalLink/></a></div></motion.article></section>
<section id="achievements" className="section"><Title n="05" k="ACHIEVEMENTS" t="Building, competing and winning."/><div className="achievements">{[['2026','1st Place','Creative Sparks Challenge','HydroMap — flood-risk prediction and safer routing.'],['2025','2nd Place','PSU ACM AI Hackathon','SignCare — AI-powered sign-language communication.'],['2025','Top 50','AI League by SCAI','Stadium Sound — live commentary translated into sign language.'],['2024','2nd Place','WiDS Datathon','Predictive modeling challenge using an 18K-record dataset.']].map(a=><motion.article key={a[2]} className="achievement" {...fade}><div className="achievement-date"><CalendarDays/><time>{a[0]}</time></div><b><Trophy/>{a[1]}</b><h3>{a[2]}</h3><p>{a[3]}</p></motion.article>)}</div></section>
<section id="skills" className="section"><Title n="06" k="SKILLS & CREDENTIALS" t="A toolkit for applied AI."/><div className="skills">{[['AI & Machine Learning',['Python','Machine Learning','Deep Learning','Model Evaluation','Forecasting']],['LLMs & Intelligent Systems',['LLMs','RAG','Embeddings','Reranking','AI Agents','Prompt Engineering']],['Computer Vision & Data',['YOLO','ByteTrack','OpenCV','CNNs','SQL','Data Analysis']],['Development',['FastAPI','APIs','Git','GitHub','AI System Integration']]].map(g=><div key={g[0]} className="skill"><h3>{g[0]}</h3>{g[1].map(x=><span key={x}>{x}</span>)}</div>)}</div><div className="certs">{certificates.map(x=><button key={x.title} onClick={()=>setC(x)} aria-label={"View "+x.title+" certificate"}><small>{x.issuer}</small><b>{x.title}</b><span className="certificate-year">{x.year}</span><img className="certificate-preview" src={x.image} alt={x.title+" certificate preview"} loading="lazy"/><span className="certificate-open">View certificate <ExternalLink aria-hidden="true"/></span></button>)}</div></section>
<section id="contact" className="section contact"><div><div className="kicker">07 — CONTACT</div><h2>Let’s build intelligent systems.</h2><p className="lead">Open to AI, machine-learning and intelligent product opportunities, as well as research collaborations.</p></div><div className="contactbox"><a href="mailto:shurooqbawazir@gmail.com"><Mail/>shurooqbawazir@gmail.com</a><a href="https://www.linkedin.com/in/shurooq-bawazir/" target="_blank" rel="noopener noreferrer"><Linkedin/>LinkedIn</a><a href="https://github.com/shurooqbawazir4" target="_blank" rel="noopener noreferrer"><Github/>GitHub</a><span><MapPin/>Riyadh, Saudi Arabia</span></div></section></main><footer>© 2026 Shurooq Bawazir <span>Built around AI, clarity & impact.</span></footer>
{p&&<div className="modalbg" onClick={()=>setP(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setP(null)}>×</button><small>{p.category}</small><h2>{p.title}</h2><h3>{p.tagline}</h3><p>{p.description}</p><b className="award">{p.award}</b><div className="flow">{p.flow.map(x=><span key={x}>{x}</span>)}</div><div className="gallery">{p.images.map((x,i)=><img key={x} src={x} alt={p.title+" image "+(i+1)}/>)}</div></div></div>}{c&&<div className="modalbg" onClick={()=>setC(null)}><div className="modal certmodal"><button className="x" onClick={()=>setC(null)}>×</button><img src={c.image} alt={c.title+" certificate"}/></div></div>}</MotionConfig>}
